version: "2.4"
services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "4000:4000"
    env_file: .env
    volumes:
      - ./api:/app/src

  db:
    image: postgres
    ports:
      # mapping between host:container -- [EXPOSE TO HOST]:[PORT IN CONTAINER]
      - "5010:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=asdfasdf
      - POSTGRES_DB=simple_message
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - "5000:80"
    links:
      - db
    env_file:
      - .env
